#!/bin/sh

# Cleans up after the auxiliary files that were created when installing
# the magma package
#
echo "Cleaning up after installing the magma package"

for f in config.log config.status config.cache *.bck */*.bck; do
  if test -w $f ; then
    rm -f $f
  fi
done

cd src
if test -e Makefile; then make clean; rm -f Makefile; fi
